# dartool_flutter —— Flutter 专属扩展包
name: dartool_flutter
description: 'Flutter extensions for dartool: platform detection, logging, form validation and more.'
repository: https://github.com/maamagic/dartool
homepage: https://github.com/maamagic/dartool/tree/main/packages/dartool_flutter
version: 0.1.0-dev.2

resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  dartool: ^0.1.0-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0